KERNEL = kernel.elf
ISO = os.iso
CC = gcc
CFLAGS = -m32 -nostdlib -nostdinc -fno-builtin -fno-stack-protector -nostartfiles -nodefaultlibs -I./drivers
ASM = nasm
ASMFLAGS = -f elf

all: $(ISO)

$(ISO): iso/boot/$(KERNEL)
	genisoimage -R \
	-b boot/grub/stage2_eltorito \
	-no-emul-boot \
	-boot-load-size 4 \
	-A os \
	-input-charset utf8 \
	-quiet \
	-boot-info-table \
	-o $(ISO) \
	iso

iso/boot/$(KERNEL): source/loader.o source/kernel.o drivers/framebuffer.o drivers/io.o drivers/pic.o drivers/interrupt_handlers.o drivers/interrupt_asm.o drivers/interrupts.o drivers/keyboard.o drivers/hardware_interrupt_enabler.o
	ld -T source/link.ld -melf_i386 source/loader.o source/kernel.o drivers/framebuffer.o drivers/io.o drivers/pic.o drivers/interrupt_handlers.o drivers/interrupt_asm.o drivers/interrupts.o drivers/keyboard.o drivers/hardware_interrupt_enabler.o -o iso/boot/$(KERNEL)

source/loader.o: source/loader.asm
	$(ASM) $(ASMFLAGS) source/loader.asm -o source/loader.o

source/kernel.o: source/kernel.c
	$(CC) $(CFLAGS) -c source/kernel.c -o source/kernel.o

drivers/framebuffer.o: drivers/framebuffer.c drivers/framebuffer.h
	$(CC) $(CFLAGS) -c drivers/framebuffer.c -o drivers/framebuffer.o

drivers/io.o: drivers/io.s
	$(ASM) $(ASMFLAGS) drivers/io.s -o drivers/io.o

drivers/pic.o: drivers/pic.c drivers/pic.h
	$(CC) $(CFLAGS) -c drivers/pic.c -o drivers/pic.o

drivers/interrupt_handlers.o: drivers/interrupt_handlers.s
	$(ASM) $(ASMFLAGS) drivers/interrupt_handlers.s -o drivers/interrupt_handlers.o

drivers/interrupt_asm.o: drivers/interrupt_asm.s
	$(ASM) $(ASMFLAGS) drivers/interrupt_asm.s -o drivers/interrupt_asm.o

drivers/interrupts.o: drivers/interrupts.c drivers/interrupts.h
	$(CC) $(CFLAGS) -c drivers/interrupts.c -o drivers/interrupts.o

drivers/keyboard.o: drivers/keyboard.c drivers/keyboard.h
	$(CC) $(CFLAGS) -c drivers/keyboard.c -o drivers/keyboard.o

drivers/hardware_interrupt_enabler.o: drivers/hardware_interrupt_enabler.s
	$(ASM) $(ASMFLAGS) drivers/hardware_interrupt_enabler.s -o drivers/hardware_interrupt_enabler.o

run: $(ISO)
	qemu-system-i386 -nographic -serial mon:stdio -boot d -cdrom $(ISO) -m 32

clean:
	rm -f source/*.o drivers/*.o iso/boot/$(KERNEL) $(ISO) log0.txt

.PHONY: all run clean
